import shutil
from pathlib import Path
import streamlit as st

from analyzer import analyze_logs, summarize_logs
from archive_utils import extract_uploaded_file
from ollama_client import ask_ollama
from rag_engine import LogRAG


st.set_page_config(
    page_title="Kubernetes AI Log Analyzer",
    page_icon="🔍",
    layout="wide",
)

st.title("Kubernetes AI Log Analyzer")
st.caption(
    "Local Kubernetes and Linux log analysis using "
    "deterministic rules, RAG retrieval, and Ollama."
)

with st.sidebar:
    st.header("Ollama Configuration")

    ollama_host = st.text_input(
        "Ollama URL",
        value="http://localhost:11434",
    )
    llm_model = st.text_input(
        "LLM Model",
        value="llama3.2:1b",
    )
    embedding_model = st.text_input(
        "Embedding Model",
        value="nomic-embed-text",
    )
    top_k = st.slider(
        "RAG results",
        min_value=2,
        max_value=10,
        value=5,
    )
    st.divider()

    st.header("Data Management")

    #if st.button("🗑️ Clear Uploaded Files"):
    #    upload_dir = Path("data/uploads")

    #    if upload_dir.exists():
    #        shutil.rmtree(upload_dir)

    #    upload_dir.mkdir(parents=True, exist_ok=True)

    #    st.success("Uploaded files cleared.")
    #    st.rerun()

    if st.button("🗄️ Clear Database"):
        chroma_dir = Path("data/chroma")
        if chroma_dir.exists():
            shutil.rmtree(chroma_dir)

        chroma_dir.mkdir(parents=True, exist_ok=True)

        st.session_state.rag = None

        st.success("RAG database cleared.")
        st.rerun()

    if st.button("🧹 Clear Everything"):
        upload_dir = Path("data/uploads")
        chroma_dir = Path("data/chroma")

        if upload_dir.exists():
            shutil.rmtree(upload_dir)

        if chroma_dir.exists():
            shutil.rmtree(chroma_dir)

        upload_dir.mkdir(parents=True, exist_ok=True)
        chroma_dir.mkdir(parents=True, exist_ok=True)

        st.session_state.rag = None

        st.success("Uploaded files and RAG database cleared.")
        st.rerun()

if "rag" not in st.session_state:
    st.session_state.rag = None

if "files_cleared" not in st.session_state:
    st.session_state.files_cleared = False

uploaded_files = st.file_uploader(
    "Upload log files or ZIP/TAR archives",
    type=[
        "log",
        "txt",
        "out",
        "err",
        "json",
        "yaml",
        "yml",
        "zip",
        "tar",
        "gz",
        "tgz",
    ],
    accept_multiple_files=True,
)

if not uploaded_files:
    st.info(
        "Upload one or more Kubernetes/application logs, "
        "or a ZIP/TAR archive containing logs."
    )
    st.markdown(
        """
### Supported input

Individual files:

- `.log`
- `.txt`
- `.out`
- `.err`
- `.json`
- `.yaml`
- `.yml`

Archives:

- `.zip`
- `.tar`
- `.tar.gz`
- `.tgz`

### Kubernetes examples

You can upload output generated by:

```bash
kubectl logs <pod>
kubectl logs <pod> --previous
kubectl describe pod <pod>
kubectl get events --sort-by=.lastTimestamp
```
"""
    )
    st.stop()

all_files = []
processing_errors = []

for uploaded in uploaded_files:
    try:
        extracted = extract_uploaded_file(uploaded)
        all_files.extend(extracted)
    except Exception as exc:
        processing_errors.append(f"{uploaded.name}: {exc}")

if processing_errors:
    st.warning("Some files could not be processed.")
    for error in processing_errors:
        st.write(f"- {error}")

if not all_files:
    st.error("No readable log files were found.")
    st.stop()

st.subheader("Uploaded Files")
file_table = [
    {
        "File": filename,
        "Lines": len(content.splitlines()),
        "Characters": len(content),
    }
    for filename, content in all_files
]
st.dataframe(file_table, use_container_width=True)

combined_sections = [
    f"""
===============================
FILE: {filename}

{content}
"""
    for filename, content in all_files
]
combined = "\n\n".join(combined_sections)

st.subheader("Log Statistics")
summary = summarize_logs(combined)
col1, col2, col3, col4 = st.columns(4)
col1.metric("Files", len(all_files))
col2.metric("Log Lines", summary["total_lines"])
col3.metric("Error Lines", summary["error_lines"])
col4.metric("Warning Lines", summary["warning_lines"])

st.subheader("Automated Kubernetes Analysis")
findings = analyze_logs(combined)

if findings:
    for finding in findings:
        severity = finding["severity"]
        message = (
            f"{finding['issue']} — "
            f"{finding['match_count']} matching lines"
        )

        if severity == "CRITICAL":
            st.error(message)
        elif severity == "HIGH":
            st.warning(message)
        else:
            st.info(message)

        st.markdown(f"**Likely Cause:** {finding['cause']}")

        with st.expander(f"Evidence — {finding['issue']}"):
            for line in finding["evidence"]:
                st.code(line, language="text")

        with st.expander(
            f"Suggested kubectl Investigation — {finding['issue']}"
        ):
            for command in finding["commands"]:
                st.code(command, language="bash")
else:
    st.success("No known Kubernetes failure pattern was detected.")

if summary["errors"]:
    with st.expander("Detected Error Lines"):
        for line in summary["errors"]:
            st.code(line, language="text")

if summary["warnings"]:
    with st.expander("Detected Warning Lines"):
        for line in summary["warnings"]:
            st.code(line, language="text")

st.subheader("AI / RAG Analysis")
st.write(
    "The RAG engine indexes the uploaded logs and retrieves relevant "
    "evidence before sending it to Ollama."
)

if "rag" not in st.session_state:
    st.session_state.rag = None

if st.button("Index Logs", type="primary"):
    try:
        with st.spinner("Creating embeddings and indexing logs..."):
            rag = LogRAG(
                ollama_url=ollama_host,
                embedding_model=embedding_model,
            )
            chunk_count = rag.index_logs(all_files)
            st.session_state.rag = rag

        st.success(f"Successfully indexed {chunk_count} log chunks.")
    except Exception as exc:
        st.error("RAG indexing failed.")
        st.exception(exc)

if st.session_state.rag is not None:
    st.markdown("### Ask a Question")
    user_question = st.text_area(
        "Question",
        value=(
            "What is the most likely root cause of the Kubernetes failure? "
            "Provide evidence from the logs and recommended troubleshooting "
            "steps."
        ),
        height=120,
    )

    if st.button("Ask Ollama"):
        try:
            with st.spinner(
                "Retrieving relevant logs and analyzing with Ollama..."
            ):
                documents = st.session_state.rag.search(
                    user_question,
                    k=top_k,
                )
                context_parts = []
                for doc in documents:
                    filename = doc.metadata.get("filename", "unknown")
                    context_parts.append(
                        f"SOURCE FILE: {filename}\n\n{doc.page_content}"
                    )
                context = "\n\n".join(context_parts)

                deterministic_parts = []
                for finding in findings:
                    evidence = "\n".join(finding["evidence"])
                    commands = "\n".join(finding["commands"])
                    deterministic_parts.append(
                        f"Issue: {finding['issue']}\n"
                        f"Severity: {finding['severity']}\n"
                        f"Likely Cause: {finding['cause']}\n"
                        f"Evidence:\n{evidence}\n"
                        f"Suggested Commands:\n{commands}"
                    )

                deterministic_analysis = (
                    "\n\n".join(deterministic_parts)
                    if deterministic_parts
                    else "No deterministic Kubernetes failure pattern detected."
                )

                prompt = f"""
You are a Kubernetes reliability engineer analyzing uploaded logs.

Answer the user's question using only the supplied evidence. Clearly
separate observed evidence from hypotheses. Recommend practical kubectl
commands where appropriate, and do not invent events or metrics.

USER QUESTION:
{user_question}

RETRIEVED LOG CONTEXT:
{context}

DETERMINISTIC ANALYSIS:
{deterministic_analysis}
"""
                answer = ask_ollama(
                    prompt,
                    model=llm_model,
                    host=ollama_host,
                )

            st.markdown("### Ollama Analysis")
            st.markdown(answer)
        except Exception as exc:
            st.error("Ollama analysis failed.")
            st.exception(exc)
